### ISSUE TITLE
TikTok still not working properly

### ISSUE THREAD

**Issue by sh230941** [freezingdata/snh-userscript-tiktok#6]
Hello,

as recommendet I installed and tried the new brach for the TikTok-Module.
While using the new Version of the Module, I recogniced there are still some issues with it.
It seems like the Program still isn´t recognising some Profiles and therefore these can´t be scraped. One example is the TikTok-page of "billieeilish".
The other problem is that the Program isn´t properly recognising the Commentaries (and therefor isn´t saving the accounts).
In the overview (posting explorer) the number of Comments is listed, but when checking one Posting there are no Comments listet, while the Screenshoot is showing the Comments. This leads to the user Profiles (that commented) not being "targeted" and listet in the data explorer.

**Comment by freezingdata** [comment]
At first, thank you for your ongoing paticipation. 
And thank you for the desturbing experience of the **_billieeilish_** TikTok page :-)

I can confirm, that there is an issue with the detection of some tiktok pages. There some small differences in the HTML sourcecode of some of the profile pages. We fixed this issue in the latest commit. 

But I can't confirm the issue with the comment collection. I've tested it with a logged in account, and with no account looged in.  Both results are quite good. 

I released an new commit in this branch: https://github.com/freezingdata/snh-userscript-tiktok/tree/rewrite-and-captcha-solver

I you have already issues with comments, please add the SNH file and a logfile in this thread. I will take a deeper look into it.

**Comment by sh230941** [comment]
Danke, alles klar - der neue Zweig hat das Problem gelöst.
