### ISSUE TITLE
Can not find snhwalker_utils

### ISSUE THREAD

**Issue by thisistorsten** [freezingdata/snh-userscript-tiktok#7]
Hi,

how can i resolve this missing package?

Best regards

**Comment by freezingdata** [comment]
Hello Thorsten,

did you use the module with the Social Network Harvester Software. The missing package ist included in the SNH installation. 

Best regards

**Comment by thisistorsten** [comment]
No i checked out your code from GitHub only. How can i get the mentioned
Software?

Freezingdata GmbH ***@***.***> schrieb am Mi., 21. Dez. 2022,
21:56:

**Comment by thisistorsten** [comment]
???

**Comment by freezingdata** [comment]
Hello Thorsten,
sorry for the late response. 

Please contact our sales team to acquire a test license. info@freezingdata.de

Best regards
